# Assignment 2: solving linear equation systems

In [98]:
import numpy as np
def getCoefficient(equation, variable):
    i = 0
    n = 0
    power = 1
    length = len(equation)
    
    while i < length and not(equation[i] == variable):
        i = i + 1
    if i >= len(equation):
        return 0
    
    i = i - 1
    if i < 0 or equation[i] == ' ' or equation[i] == '\t':
        return 1
    while equation[i] >= '0' and equation[i] <= '9' and i > -1:
        n = n + int(equation[i]) * power
        power = power * 10
        i = i - 1
    return n

def solveEquations(equations):
    A = np.zeros((3, 3))
    B = np.zeros((3, 1))
    variables = ['x', 'y', 'z']
    
    for i in range(0, 3):
        # Equation i
        for j in range(0, 3):
            A[i][j] = getCoefficient(equations[i], variables[j])
        B[i][0] = getCoefficient(equations[i], ';')
        
    print("Coefficient matrix:\n{0}".format(A))
    print("Constant sum matrix:\n{0}".format(B))
    
    X = np.linalg.solve(A, B)
    print("x = {0}".format(float(X[0][0])))
    print("y = {0}".format(float(X[1][0])))
    print("z = {0}".format(float(X[2][0])))

In [104]:
print("----------------\nProblem 1")
solveEquations(["2x + 7y + z = 40;", "3x + y + 4z = 15;", "x + 5y + 3z = 30;"])
print("----------------\nProblem 2")
solveEquations(["3x + 2y + 7z = 8;", "4x + 2y + 5z = 9;", "2x + 5y + 2z = 12;"])
print("----------------\nProblem 3")
solveEquations(["7x + y + z = 15;", "2xy + z = 4;", "3x + 2y + 4z = 29;"])
print("----------------\nProblem 4")
solveEquations(["2x + y + 6z = 7;", "4x + 3y + z = 8;", "x + 3y + 5z = 9;"])
print("----------------\nProblem 5")
solveEquations(["2x + y + 5z = 26;", "x + y + z = 7;", "3x + 5y + 2z = 22;"])
print("----------------\nProblem 6")
solveEquations(["7x − y + z = 4;", "5x − 2y + 2z = −1;", "3x + 2y + z = 6;"])

----------------
Problem 1
Coefficient matrix:
[[2. 7. 1.]
 [3. 1. 4.]
 [1. 5. 3.]]
Constant sum matrix:
[[40.]
 [15.]
 [30.]]
x = 2.0000000000000013
y = 5.0
z = 0.9999999999999992
----------------
Problem 2
Coefficient matrix:
[[3. 2. 7.]
 [4. 2. 5.]
 [2. 5. 2.]]
Constant sum matrix:
[[ 8.]
 [ 9.]
 [12.]]
x = 1.188679245283019
y = 1.8867924528301887
z = 0.09433962264150944
----------------
Problem 3
Coefficient matrix:
[[7. 1. 1.]
 [2. 0. 1.]
 [3. 2. 4.]]
Constant sum matrix:
[[15.]
 [ 4.]
 [29.]]
x = 0.5999999999999999
y = 8.0
z = 2.8000000000000003
----------------
Problem 4
Coefficient matrix:
[[2. 1. 6.]
 [4. 3. 1.]
 [1. 3. 5.]]
Constant sum matrix:
[[7.]
 [8.]
 [9.]]
x = 0.593220338983051
y = 1.6440677966101693
z = 0.6949152542372882
----------------
Problem 5
Coefficient matrix:
[[2. 1. 5.]
 [1. 1. 1.]
 [3. 5. 2.]]
Constant sum matrix:
[[26.]
 [ 7.]
 [22.]]
x = -0.9999999999999979
y = 2.999999999999999
z = 4.999999999999999
----------------
Problem 6
Coefficient matrix:
[[7. 1. 