In [2]:
# Imports for all the below operations...
from numpy import matrix, zeros, linalg

# 

In [4]:
# EQUATION SYSTEM SOLVER FUNCTIONS...

# Reads the equation strings and converts them into lists of various values...
def getLists(equationList):
    var, coef, const, varCount, eqCount = {}, [], [], 0, 0
    for e in equationList:
        e, i, varsFound, sign = e + "\\", 0, [], 1
        # If coefficient of a variable is to the right of "=", we will take it to the LHS, reversing its sign.
        # If constant term is to the left of "=", we will take it to the RHS, reversing its sign.
        
        # Going through the equation...
        while e[i] != "\\":
            coefValue = ""
            while e[i].isspace(): i = i + 1 # To traverse possible spaces before '-'.
            if e[i] == "-": coefValue, i = coefValue + "-", i + 1 # Negative sign detection.
            while e[i].isspace(): i = i + 1 # To traverse possible spaces after '-'.
            
            # Number encountered...
            if e[i].isnumeric():
                coefValue, i = coefValue + e[i], i + 1
                while e[i].isnumeric() and e[i] != "\\":
                    coefValue, i = coefValue + e[i], i + 1
            
            # Alphabet encountered (potential variable)...
            if e[i].isalpha():
                varName, i = e[i], i + 1
                while e[i].isalnum() and e[i] != "\\":
                    varName, i = varName + e[i], i + 1
                # If variable already encountered in equation...
                if varName in varsFound:
                    coef[var[varName]][-1] = coef[var[varName]][-1] + float(coefValue) * sign
                # If variable is newly encountered in the equation...
                else:
                    varsFound.append(varName)
                    # If the variable is newly encountered in the system...
                    if(varName not in var):
                        var[varName], varCount = varCount, varCount + 1
                        coef.append([])
                    # If no numerical coefficient specified...
                    if coefValue == "" or coefValue == "-": coefValue = coefValue + "1"
                    # Making sure zero constants are put where required...
                    l = len(coef[var[varName]])
                    while l < eqCount:
                        coef[var[varName]].append(0)
                        l = l + 1
                    coef[var[varName]].append(float(coefValue) * sign)
            
            # If a constant is identified...
            elif coefValue != "":
                # If a constant already exists in the equation...
                if "c" in varsFound:
                    const[-1] = const[-1] + float(coefValue) * -sign
                # If a constant hasn't been encountered before...
                else:
                    varsFound.append("c")
                    const.append(float(coefValue) * -sign)
            
            # If equal-to sign encountered, invert the sign variable...
            else:
                if e[i] == "=": sign = -1
                i = i + 1
        eqCount = eqCount + 1
        
        # Making sure zero constant sums are put where required...
        if len(const) < eqCount: const.append(0)
    return (coef, const, var)

# Uses the lists of values from "getLists" and creates the necessary matrices...
def getMatrices(equationList):
    (coef, const, var) = getLists(equationList)
    nVar, nEq = len(coef), len(const)
    A = zeros((nEq, nVar))
    B = zeros((nEq, 1))
    for i in range(0, nEq):
        for j in range(0, nVar):
            try: A[i][j] = coef[j][i]
            except: A[i][j] = 0
    for i in range(0, nEq):
        B[i][0] = const[i]
    return (A, B, var)

# Uses the matrices from "getMatrices" and finds the solutions if they exists...
def solveSystem(equationList):
    (A, B, var) = getMatrices(equationList)
    A = matrix(A)
    B = matrix(B)
    print("Coefficient matrix:")
    print(A)
    print("Constant sum matrix:")
    print(B)
    try: linalg.inv(A)
    except:
        print("Inverse of coefficient matrix does not exist.")
        print("No solutions.")
    else:
        print("Inverse of coefficient matrix exists.")
        X = linalg.solve(A, B)
        for i in var:
            print("{0} = {1}".format(i, X[var[i], 0]))

In [6]:
print("EQUATION SYSTEM SOLVER")
eq = []
print("Enter equations (enter 'stop' to stop input)...")
while True:
    inp = input(">> ")
    if inp != "stop":
        eq.append(inp)
    else: break
solveSystem(eq)

EQUATION SYSTEM SOLVER
Enter equations (enter 'stop' to stop input)...
>> 2x+3y-2z=3
>> 1-3z=y
>> x-y=z
>> stop
Coefficient matrix:
[[ 2.  3. -2.]
 [ 0. -1. -3.]
 [ 1. -1. -1.]]
Constant sum matrix:
[[ 3.]
 [-1.]
 [ 0.]]
Inverse of coefficient matrix exists.
x = 0.7333333333333334
y = 0.6
z = 0.13333333333333333


# 

In [8]:
print("Question 2a")
print("------------")
eqs = [ "x1 + 2x2 + x3 - 2x3 = -1",
        "2x1 + x2 + 4x3 = 2",
        "3x1 + 3x2 + 4x3 = 1"]
solveSystem(eqs)
print("========================")
print("Question 2b")
print("------------")
eqs = [ "8x + 5y = 9z",
        "3x + 2z = 9",
        "4y + 3z = 11x"]
solveSystem(eqs)

Question 2a
------------
Coefficient matrix:
[[ 1.  2. -1.]
 [ 2.  1.  4.]
 [ 3.  3.  4.]]
Constant sum matrix:
[[-1.]
 [ 2.]
 [ 1.]]
Inverse of coefficient matrix exists.
x1 = 1.6666666666666679
x2 = -1.3333333333333341
x3 = -3.7007434154171906e-16
Question 2b
------------
Coefficient matrix:
[[  8.   5.  -9.]
 [  3.   0.   2.]
 [-11.   4.   3.]]
Constant sum matrix:
[[0.]
 [9.]
 [0.]]
Inverse of coefficient matrix exists.
x = 1.4036697247706422
y = 2.064220183486239
z = 2.3944954128440368


# 

In [9]:
# Let x and y be the price of mangoes and oranges respectively.
day1 = "20x + 10y = 350"
day2 = "17x + 22y = 500"
solveSystem([day1, day2])

Coefficient matrix:
[[20. 10.]
 [17. 22.]]
Constant sum matrix:
[[350.]
 [500.]]
Inverse of coefficient matrix exists.
x = 10.0
y = 15.0


Hence, price of 1 mango is 10 and price of 1 orange is 15.

# 

We say that a square matrix is invertible if and only if the determinant is not equal to zero.

In [6]:
# Support functions...
def inputPositiveInteger(prompt):
    while True:
        try:
            i = input(prompt)
            if i == "x": return 0
            i = int(i)
            if i <= 0: i = 1/0
            return i
        except:
            print("Invalid integer, please re-enter.")
def floatInput(prompt):
    while True:
        try:
            i = float(input(prompt))
            return i
        except:
            print("Invalid number, please re-enter.")
def matrixInput(nRow, nCol):
    print("\nEnter row by row, each element in the row separated by comma...")
    A, i = zeros((nRow, nCol)), 0
    while i < nRow:
        row = input("R{0}: ".format(i + 1)).split(",")
        if "x" in row: break # To stop inputting anymore
        if len(row) != nCol:
            print("ERROR: You must only enter", nCol, "per row")
            continue
        for j in range(0, nCol):
            try:
                A[i][j] = float(row[j])
            except:
                print("ERROR: Non-numeric inputs.")
                j = -1
                break
        if j != -1: i = i + 1
    return A

In [7]:
nRow = inputPositiveInteger("No. of rows? ")
nCol = inputPositiveInteger("No. of columns? ")
M = matrix(matrixInput(nRow, nCol))
print("Your matrix:")
print(M)
if(nRow != nCol) or linalg.det(M) == 0:
    print("This matrix is not invertible.")
else:
    print("This matrix is invertible.")

No. of rows? 2
No. of columns? 3

Enter row by row, each element in the row separated by comma...
R1: 2,3,4
R2: 2,7,3
Your matrix:
[[2. 3. 4.]
 [2. 7. 3.]]
This matrix is not invertible.


# 

Different ways to solve a system of equations...

In [9]:
eq = ["3x + 6y - 4z = -3",
      "5 - 5z + y = x",
      "7x + 9y - 16z = 0"]
(A, B, var) = getMatrices(eq)
A = matrix(A)
B = matrix(B)

In [10]:
# Method 1
print("\nMethod 1 solutions:")
X = linalg.inv(A)*B
for i in var:
    print("{0} = {1}".format(i, X[var[i], 0]))
# Method 2
print("\nMethod 2 solutions:")
X = linalg.solve(A, B)
for i in var:
    print("{0} = {1}".format(i, X[var[i], 0]))
# Method 2
print("\nMethod 2 solutions:")
X = A**(-1)*B
for i in var:
    print("{0} = {1}".format(i, X[var[i], 0]))


Method 1 solutions:
x = 2.4967741935483874
y = -1.6322580645161289
z = 0.17419354838709689

Method 2 solutions:
x = 2.496774193548387
y = -1.6322580645161289
z = 0.17419354838709686

Method 2 solutions:
x = 2.4967741935483874
y = -1.6322580645161289
z = 0.17419354838709689
