In [1]:
import numpy as np

# Computation on NumPy

NumPy allows for operations on whole arrays, which vastly increases the operation speed with respect to looping.

## Array arithmetic

In [5]:
alpha = np.array([1, 2, 3, 10, 12])

In [20]:
print("\nBINARY OPERATIONS")
print("alpha:", alpha)
print("alpha + 7:", alpha + 7)
print("alpha - 7:", alpha - 7)
print("alpha * 7:", alpha * 7)
print("alpha / 7:", alpha / 7)
print("alpha % 7:", alpha % 7)

print("\nUNARY OPERATIONS")
print("-alpha:", -alpha)
print("alpha**2:", alpha**2)

print("\nCOMPOSITE OPERATION RESULTS")
print((alpha**2 - 12) % 13)
print((alpha - 2) % 3 + (alpha * 2))


BINARY OPERATIONS
alpha: [1 5 2]
alpha + 7: [ 8 12  9]
alpha - 7: [-6 -2 -5]
alpha * 7: [ 7 35 14]
alpha / 7: [0.14285714 0.71428571 0.28571429]
alpha % 7: [1 5 2]

UNARY OPERATIONS
-alpha: [-1 -5 -2]
alpha**2: [ 1 25  4]

COMPOSITE OPERATION RESULTS
[2 0 5]
[ 4 10  4]


# Masking

Masking is used to extract, modify, count or generally manipulate values in an array based on some criterion. For example, you may want to count the number of values greater than a certain value, or remove all values that are above some threshold (outliers). In NumPy, Boolean masking is generally the most efficient way to accomplish these kinds of tasks.

Performing conditional operations on arrays results in an array with Boolean values based on whether the corresponding value in the array satisfies the condition. For example...

In [22]:
alpha = np.array([1, 5, 2])
print("alpha:", alpha)
print("alpha % 2 == 0:", alpha % 2 == 0)

alpha: [1 5 2]
alpha % 2 == 0: [False False  True]


We can retrieve the 'True' values i.e. the values that satisfy the condition in the following way...

In [25]:
print(alpha[alpha % 2 == 0])
# Or, you can assign 'alpha % 2 == 0' to another variable to create a Boolean array.
# Then, you can give this array as the reference (same thing, ultimately).

[2]


Conditional operators involving two arrays will compare values in matching indices...

In [31]:
alpha = np.array([1, 2, 3])
beta = np.array([1, 0, 3])
print("alpha:", alpha)
print("beta:", beta)
print("alpha == beta", alpha == beta)
print("Values in alpha satisfying alpha == beta:", alpha[alpha == beta])

alpha: [1 2 3]
beta: [1 0 3]
alpha == beta [ True False  True]
Values in alpha satisfying alpha == beta: [1 3]


When using logical operators ('and' and 'or') in NumPy arrays, use the conventional programming symbols '&' and '|' and not the keywords themselves (as doing so will result in a ValueError with the message "The truth value of an array with more than one element is ambiguous. Use a.any( ) or a.all( )", which means you can still use 'and' and 'or' but will need to use some functions to process the data first)...

In [33]:
try: print((alpha >= 2) and (beta >= 2))
except ValueError:
    print("Using 'and' won't work!")
    print("(alpha >= 2) & (beta >= 2):", (alpha >= 2) & (beta >= 2))

Using 'and' won't work!
(alpha >= 2) & (beta >= 2): [False False  True]


# Fancy indexing

This goes beyond slicing, and increases the ability to refer to array elements comprehensively, specficially and efficiently.

## Group of specific indices referred together

You can reference multiple specific indices through a list...

In [45]:
alpha = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("alpha:", alpha)
print("1st, 3rd and 5th elements:", alpha[[0, 2, 4]])

alpha: [1 2 3 4 5 6 7 8]
1st, 3rd and 5th elements: [1 3 5]


Note that when using fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed...

In [50]:
print("1st, 3rd and 5th elements in one row, and 2nd, 4th and 6th elements in the next row:")
indices = np.array([[0, 2, 4], [1, 3, 5]])
print(alpha[indices])

1st, 3rd and 5th elements in one row, and 2nd, 4th and 6th elements in the next row:
[[1 3 5]
 [2 4 6]]


### For multidimensional arrays

In [60]:
# 2D array...
beta = np.array([[1, 2, 3], [20, 40, 60], [300, 600, 900]])
print("beta:\n", beta)

beta:
 [[  1   2   3]
 [ 20  40  60]
 [300 600 900]]


In [62]:
print("Elements in (1, 2), (2, 3) and (3, 3)")
print("(Coordinates are given in form (x, y))")
rows = [0, 1, 2]
cols = [1, 2, 2]
print(beta[rows, cols])

Elements in (1, 2), (2, 3) and (3, 3)
(Coordinates are given in form (x, y))
[  2  60 900]


## Combining fancy indexing with simple indexing and slicing

In [67]:
beta = np.array([[1, 2, 3], [20, 40, 60], [300, 600, 900]])
print("beta:\n", beta)

beta:
 [[  1   2   3]
 [ 20  40  60]
 [300 600 900]]


In [69]:
print(beta[1, [0, 1, 2]])

[20 40 60]


Here, the row is always index 1 i.e. row 2, and the column indices are 0, 1 and 2 respectively (i.e. columns 1, 2 and 3 respectively).

In [70]:
print(beta[0:2, [0, 1, 2]])

[[ 1  2  3]
 [20 40 60]]


Here, the rows are from index 0 to 2 i.e. rows 1 to 3, and the column indices are 0, 1 and 2 respectively (i.e. columns 1, 2 and 3 respectively).