# Sem 4, Assignment 1

## Question 1

Verify the property $sin(ai)=isinh(a)$

In [55]:
import cmath as cm
print("The given formula is\nsin(ai) = isinh(a)")
a = float(input("Enter the value of a: "))
print("The following is the answer to whether the LHS equals the RHS...")
cm.sin(a * complex(0, 1)) == complex(0, 1)*cm.sinh(a)

The given formula is
sin(ai) = isinh(a)
Enter the value of a: 2
The following is the answer to whether the LHS equals the RHS...


True

## Question 2

Verify the property $e^{iq} = cos(q) + isin(q)$

In [54]:
import cmath as cm
print("Euler's formula is\ne^(iq) = cos(q) + isin(q)")
q = float(input("Enter the value of q: "))
print("The following is the answer to whether the LHS equals the RHS...")
cm.exp(complex(0, 1) * q) == cm.cos(q) + complex(0, 1)*cm.sin(q)

Euler's formula is
e^(iq) = cos(q) + isin(q)
Enter the value of q: 65
The following is the answer to whether the LHS equals the RHS...


True

## Question 3

Write a python program to define a 4x4 matrix (user defined) and compute some operations.

In [39]:
import numpy as np
A = np.zeros((4, 4))
for i in range(0, 4):
    for j in range(0, 4):
        while True:
            try:
                x = float(input("Enter value at row {0} column {1}: ".format(i, j)))
                A[i][j] = x
                break
            except:
                print("Invalid number, please re-enter.")
print("Your matrix is {0}\n".format(A))
print("A**2 is\n{0}".format(A**2))
print("A**2 is\n{0}".format(A + 3*A**2))
print("A**2 is\n{0}".format(A - 5*np.identity(4)))

Enter value at row 0 column 0: 2
Enter value at row 0 column 1: 4
Enter value at row 0 column 2: 1
Enter value at row 0 column 3: 7
Enter value at row 1 column 0: 4
Enter value at row 1 column 1: 7
Enter value at row 1 column 2: 9
Enter value at row 1 column 3: 4
Enter value at row 2 column 0: 6
Enter value at row 2 column 1: 9
Enter value at row 2 column 2: 4
Enter value at row 2 column 3: 5
Enter value at row 3 column 0: 5
Enter value at row 3 column 1: 3
Enter value at row 3 column 2: 0
Enter value at row 3 column 3: -5
Your matrix is [[ 2.  4.  1.  7.]
 [ 4.  7.  9.  4.]
 [ 6.  9.  4.  5.]
 [ 5.  3.  0. -5.]]

A**2 is
[[ 4. 16.  1. 49.]
 [16. 49. 81. 16.]
 [36. 81. 16. 25.]
 [25.  9.  0. 25.]]
A**2 is
[[ 14.  52.   4. 154.]
 [ 52. 154. 252.  52.]
 [114. 252.  52.  80.]
 [ 80.  30.   0.  70.]]
A**2 is
[[ -3.   4.   1.   7.]
 [  4.   2.   9.   4.]
 [  6.   9.  -1.   5.]
 [  5.   3.   0. -10.]]


## Question 4

Extract the second row and third column from the following matrix.

In [21]:
import numpy as np
A = np.matrix([[0, 1, 1, 4], [3, 6, -3, 3], [-2, -3, 7, 10]])
print("The matrix is\n{0}".format(A))
print("The 2nd row is\n{0}".format(A[1]))
print("The 3rd column is\n{0}".format(A[:, 2]))

The matrix is
[[ 0  1  1  4]
 [ 3  6 -3  3]
 [-2 -3  7 10]]
The 2nd row is
[[ 3  6 -3  3]]
The 3rd column is
[[ 1]
 [-3]
 [ 7]]
