# INTRODUCTION

If a set of vectors is linearly independent, then the only way their linear combination will equal zero is if all their scalar coefficients are zero. There are other ways to check if a set of vectors is linearly independent, based on different results. Here,I will look at two of them, and demonstrate the insufficiency of the first method...

# Using system of linear equations

We cannot use the methods for solving equations for finding the independence of a set of vectors, since the 'solve' function in the 'linalg' module in the NumPy library will only return the trivial solution (i.e. all scalars are zero) if we use the linear equation system solving methods as follows...

In [2]:
import numpy as np
v1 = np.matrix([[5], [-2], [7]])
v2 = np.matrix([[6], [-8], [3]])
v3 = np.matrix([[4], [7], [-1]])

print("\nMatrix of vectors {v1, v2, v3}:")
V = np.hstack([v1, v2, v3])
print(V)

print("\nVector of zeros:")
c = np.zeros((3, 1))
print(c)

print("\nCoefficients for v1, v2 and v3 if their linear combination is zero:")
print(np.linalg.solve(V, c))


Matrix of vectors {v1, v2, v3}:
[[ 5  6  4]
 [-2 -8  7]
 [ 7  3 -1]]

Vector of zeros:
[[0.]
 [0.]
 [0.]]

Coefficients for v1, v2 and v3 if their linear combination is zero:
[[ 0.]
 [-0.]
 [ 0.]]


The given coefficients i.e. scalars multiplied to the vectors in the given set of vectors will always be given as 0, since this is the simplest solution, and this is all the solve function looks for.

# Checking the determinant of the vector matrix

So, to check for linear independence, we use a result. Note that this result is applicable only to vector spaces that are defined over the real number field. The result is as follows...

The set of vectors S from the vector space V defined over the field of real numbers is linearly independent if and only if $|S|≠ 0$, where S is the matrix constructed from the set of vectors S.

In [18]:
import numpy as np
v1 = np.matrix([1, -2, 7])
v2 = np.matrix([6, -2, 3])
v3 = np.matrix([3, 1, -2])

print("\nMatrix of vectors V = {v1, v2, v3}:")
V = np.vstack([v1, v2, v3])
print(V)

print("\nDeterminant of V = 0?:", np.linalg.det(V) == 0)


Matrix of vectors V = {v1, v2, v3}:
[[ 1 -2  7]
 [ 6 -2  3]
 [ 3  1 -2]]

Determinant of V = 0?: False


Hence, we have that the set of vectors $\{(1,-2,7),(6,-2,3),(3,1,-2)\}$ is linearly independent.